In [15]:
import pandas as pd
import numpy as np
import datetime
Data=pd.read_csv('data_new.csv')
Data.head()

Rank                               Title  Year  Score  Metascore  \
0  3166                                 '71  2014    7.2       83.0   
1  6646                         'A' gai wak  1983    7.4       -1.0   
2  8656                       'A' gai wak 2  1987    7.2       -1.0   
3  9287           'I Know Where I'm Going!'  1945    7.6       -1.0   
4  6795  (T)Raumschiff Surprise - Periode 1  2004    5.4       -1.0   

                     Genre   Vote        Director  Runtime  Revenue  \
0  Action, Drama, Thriller  44532    Yann Demange       99     1.27   
1           Action, Comedy  12657     Jackie Chan      105    -1.00   
2    Action, Comedy, Crime   7739     Jackie Chan      101    -1.00   
3           Drama, Romance   6861  Michael Powell       91    -1.00   
4           Comedy, Sci-Fi  12158  Michael Herbig       87    -1.00   

                                         Description  Oscar  Befta  Globe  win  
0  In 1971, a young and disorientated British sol...   -1.0   -1.0   -1.0 -1.0  
1  Fighting against pirates in "old Hong Kong". C...   -1.0   -1.0   -1.0 -1.0  
2  Dragon is now transferred to be the police hea...   -1.0   -1.0   -1.0 -1.0  
3  A young Englishwoman goes to the Hebrides to m...   -1.0   -1.0   -1.0 -1.0  
4  Three hundred years in the future, Mars is col...   -1.0   -1.0   -1.0 -1.0

In [5]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(Data, test_size=0.3)
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3000 entries, 9191 to 1193
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Rank         3000 non-null   int64  
 1   Title        3000 non-null   object 
 2   Year         3000 non-null   int64  
 3   Score        3000 non-null   float64
 4   Metascore    3000 non-null   float64
 5   Genre        3000 non-null   object 
 6   Vote         3000 non-null   int64  
 7   Director     3000 non-null   object 
 8   Runtime      3000 non-null   int64  
 9   Revenue      3000 non-null   float64
 10  Description  3000 non-null   object 
 11  Oscar        3000 non-null   float64
 12  Befta        3000 non-null   float64
 13  Globe        3000 non-null   float64
 14  win          3000 non-null   float64
dtypes: float64(7), int64(4), object(4)
memory usage: 375.0+ KB


In [7]:
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
X=train[['Score', 'Revenue', 'Vote']]
y=train.Oscar
#X=train['Score']
#y=train.winner
model.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [8]:
expected = test.Oscar
predicted = model.predict(test[['Score', 'Revenue', 'Vote']])
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted,labels=[1,0,-1]))

              precision    recall  f1-score   support

        -1.0       0.85      1.00      0.92      2537
         0.0       0.27      0.02      0.04       293
         1.0       0.50      0.04      0.07       170

    accuracy                           0.85      3000
   macro avg       0.54      0.35      0.34      3000
weighted avg       0.78      0.85      0.78      3000

[[   6    9  155]
 [   4    6  283]
 [   2    7 2528]]


In [16]:
BinarData = Data
d = {-1 : False, 0: False, 1: True}
#BinarData[['win','Oscar','Befta','Globe']] = BinarData[['win','Oscar','Befta','Globe']].map(d)
BinarData['win'] = BinarData['win'].map(d)
BinarData['Oscar'] = BinarData['Oscar'].map(d)
BinarData['Befta'] = BinarData['Befta'].map(d)
BinarData['Globe'] = BinarData['Globe'].map(d)


In [23]:
train, test = train_test_split(BinarData, test_size=0.2)
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2000 entries, 4084 to 2146
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Rank         2000 non-null   int64  
 1   Title        2000 non-null   object 
 2   Year         2000 non-null   int64  
 3   Score        2000 non-null   float64
 4   Metascore    2000 non-null   float64
 5   Genre        2000 non-null   object 
 6   Vote         2000 non-null   int64  
 7   Director     2000 non-null   object 
 8   Runtime      2000 non-null   int64  
 9   Revenue      2000 non-null   float64
 10  Description  2000 non-null   object 
 11  Oscar        2000 non-null   bool   
 12  Befta        2000 non-null   bool   
 13  Globe        2000 non-null   bool   
 14  win          2000 non-null   bool   
dtypes: bool(4), float64(3), int64(4), object(4)
memory usage: 195.3+ KB


In [24]:

model = LogisticRegression()
X=train[['Score', 'Revenue', 'Vote']]
y=train.win
#X=train['Score']
#y=train.winner
model.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
expected = test.win
predicted = model.predict(test[['Score', 'Revenue', 'Vote']])
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted,labels=[True,False]))

              precision    recall  f1-score   support

       False       0.92      1.00      0.96      1845
        True       0.71      0.03      0.06       155

    accuracy                           0.92      2000
   macro avg       0.82      0.52      0.51      2000
weighted avg       0.91      0.92      0.89      2000

[[   5  150]
 [   2 1843]]
